export default [{
  name: `Joe Cotton`,
  skills: {
    Java: 9,
    CSharp: 2,
    React: 4,
    Vue: 6,
    Node: 2,
    Flutter: 1,
    ReactNative: 3,
    AzureDevOps: 7,
    AWS: 5,
    Mongo: 9,
    SQL: 8,
  },
  available: false,
  dateAvailable: "5/6/22",
  project: `Crucial Learning`,
}, {
  name: `Jordan Cotter`,
  skills: {
    Java: 2,
    CSharp: 3,
    React: 9,
    Vue: 9,
    Node: 10,
    Flutter: 2,
    ReactNative: 3,
    AzureDevOps: 6,
    AWS: 4,
    Mongo: 10,
    SQL: 7,
  },
  available: true,
  dateAvailable: "3/25/22",
  project: ``,
}, {
  name: `Adam Koksal`,
  skills: {
    Java: 4,
    CSharp: 1,
    React: 4,
    Vue: 10,
    Node: 10,
    Flutter: 3,
    ReactNative: 1,
    AzureDevOps: 4,
    AWS: 6,
    Mongo: 8,
    SQL: 5,
  },
  available: false,
  dateAvailable: "10/15/22",
  project: `Crucial Learning`,
}, {
  name: `Bob Vance`,
  skills: {
    Java: 10,
    CSharp: 3,
    React: 5,
    Vue: 7,
    Node: 3,
    Flutter: 4,
    ReactNative: 4,
    AzureDevOps: 1,
    AWS: 3,
    Mongo: 5,
    SQL: 2,
  },
  available: false,
  dateAvailable: "4/6/22",
  project: `UVU`,
}, {
  name: `Stephen Pace`,
  skills: {
    Java: 9,
    CSharp: 5,
    React: 9,
    Vue: 8,
    Node: 7,
    Flutter: 9,
    ReactNative: 8,
    AzureDevOps: 5,
    AWS: 7,
    Mongo: 9,
    SQL: 6,
  },
  available: false,
  dateAvailable: "5/6/23",
  project: `UVU`,
}, {
  name: `Rod Johnson`,
  skills: {
    Java: 6,
    CSharp: 10,
    React: 2,
    Vue: 6,
    Node: 1,
    Flutter: 4,
    ReactNative: 1,
    AzureDevOps: 8,
    AWS: 3,
    Mongo: 4,
    SQL: 9,
  },
  available: false,
  dateAvailable: "5/6/24",
  project: `Rational Alliance`,
}, {
  name: `John Galt`,
  skills: {
    Java: 10,
    CSharp: 10,
    React: 10,
    Vue: 10,
    Node: 10,
    Flutter: 10,
    ReactNative: 10,
    AzureDevOps: 10,
    AWS: 10,
    Mongo: 10,
    SQL: 10,
  },
  available: true,
  dateAvailable: "1/6/22",
  project: ``,
}, {
  name: `Marcus Cantu`,
  skills: {
    Java: 8,
    CSharp: 4,
    React: 6,
    Vue: 5,
    Node: 9,
    Flutter: 5,
    ReactNative: 9,
    AzureDevOps: 6,
    AWS: 5,
    Mongo: 7,
    SQL: 7,
  },
  available: false,
  dateAvailable: "4/6/22",
  project: `Rational Alliance`,
}] 